stages:
  - build
  - sonarqube-check
  - deploy

variables:
  VM_IP: "192.168.75.120"
  REMOTE_FRONT_PATH: "/var/www/ellevent"
  REMOTE_BACK_PATH: "/home/gitlabci/backend.jar"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"

cache:
  paths:
    - .sonar/cache
    - .m2/repository
    - node_modules/

# 🔹 BUILD FRONT
build_front:
  stage: build
  image: node:22-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

# 🔹 BUILD BACK + SONAR
sonarqube-check:
  stage: sonarqube-check
  image: maven:3-eclipse-temurin-21
  before_script:
    - mkdir -p ~/.m2
    - |
      cat > ~/.m2/settings.xml << 'EOF'
      <settings>
        <proxies>
          <proxy>
            <id>lyon1-proxy</id>
            <active>true</active>
            <protocol>http</protocol>
            <host>proxy.univ-lyon1.fr</host>
            <port>3128</port>
          </proxy>
        </proxies>
      </settings>
      EOF
  script:
    - cd backend
    - mvn dependency:go-offline
    - mvn dependency:copy-dependencies -DoutputDirectory=target/dependency
    - mvn clean verify
    - mvn sonar:sonar -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    - main

# 🔹 DEPLOY FRONT
deploy_front:
  stage: deploy
  image: node:22-alpine
  before_script:
    - apk add --no-cache openssh-client
    - chmod 400 "$CI_SSH_KEY"
  script:
    - scp -o StrictHostKeyChecking=no -i "$CI_SSH_KEY" -r dist/* "gitlabci@${VM_IP}:${REMOTE_FRONT_PATH}/"
  dependencies:
    - build_front
  only:
    - main

# 🔹 DEPLOY BACKEND
deploy_backend:
  stage: deploy
  image: maven:3-eclipse-temurin-21
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - chmod 400 "$CI_SSH_KEY"
  script:
    - scp -o StrictHostKeyChecking=no -i "$CI_SSH_KEY" backend/target/*.jar "gitlabci@${VM_IP}:${REMOTE_BACK_PATH}"
    - |
      ssh -o StrictHostKeyChecking=no -i "$CI_SSH_KEY" gitlabci@${VM_IP} '
        pkill -f backend.jar || true &&
        nohup java -jar /home/gitlabci/backend.jar > /home/gitlabci/backend.log 2>&1 &
      '
  dependencies:
    - sonarqube-check
  only:
    - main