services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ellevent2026
      - POSTGRES_DB=gp2m1
    ports:
      - "5432:5432"
    volumes:
      - ./database/code.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gp2m1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate