sonar.projectKey=m1if10-2025-g02_gp2m1_AZ0gpAA6pItf3KCWeG_Y
sonar.projectName=gp2M1
sonar.host.url=https://sonar.info.univ-lyon1.fr
sonar.login=${SONAR_TOKEN}

sonar.sources=src,backend/src/main
sonar.exclusions=dist/**,node_modules/**,backend/target/**

sonar.java.binaries=backend/target/classes