# --- Configuration de la Base de Données LOCALE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/gp2m1
spring.datasource.username=postgres
spring.datasource.password=ellevent2026

# --- Configuration Hibernate (JPA) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true